---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Fu1sh.
--- DateTime: 2024/8/16 22:42
---
local voucherId = ARGV[1]
local userId = ARGV[2]

local stockKey = 'seckill:map:'..voucherId
local orderKey = 'seckill:order:'..voucherId

if (tonumber(redis.call('hget', stockKey, 'stock')) <= 0) then
    return 1
end

if (redis.call('sismember', orderKey, userId) == 1) then
    return 2
end

redis.call('hincrby', stockKey, 'stock', -1)
redis.call('sadd', orderKey, userId)
return 0